In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2

In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.0183, -1.9996, -0.2502],
        [ 0.5886,  0.1104, -1.5854]], requires_grad=True)
tensor([ 0.4240, -0.8525], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-145.6481,  -18.6588],
        [-193.2251,  -39.0387],
        [-283.6336,  -26.8004],
        [ -96.6862,    5.2724],
        [-210.3210,  -60.6167]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(47650.7773, grad_fn=<DivBackward0>)


In [11]:
# Compute gradients
loss.backward()

In [12]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.0183, -1.9996, -0.2502],
        [ 0.5886,  0.1104, -1.5854]], requires_grad=True)
tensor([[-21685.8125, -25355.4883, -15179.5762],
        [ -9749.6055, -11656.8594,  -7158.0654]])


In [13]:
w
w.grad

tensor([[-21685.8125, -25355.4883, -15179.5762],
        [ -9749.6055, -11656.8594,  -7158.0654]])

In [14]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [15]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(47650.7773, grad_fn=<DivBackward0>)


In [16]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [17]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-106.2995,   -0.6523],
        [-141.4606,  -15.3262],
        [-221.9838,    1.4548],
        [ -58.0448,   22.8791],
        [-160.3882,  -37.6871]], grad_fn=<AddBackward0>)


In [18]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(32845.8203, grad_fn=<DivBackward0>)


In [19]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-17619.1445, -20973.9238, -12478.4492],
        [ -7887.8955,  -9649.3242,  -5920.6230]])
tensor([-213.8354,  -97.8663])


In [20]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [21]:
print(w)
print(b)

tensor([[ 0.3747, -1.5363,  0.0263],
        [ 0.7650,  0.3235, -1.4546]], requires_grad=True)
tensor([ 0.4288, -0.8504], requires_grad=True)


In [22]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(22860.4961, grad_fn=<DivBackward0>)


In [23]:
# Train for 100 epochs
for i in range(10000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [24]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.5083, grad_fn=<DivBackward0>)


In [25]:
# Predictions
preds

tensor([[ 57.2361,  70.1678],
        [ 82.1628, 100.7577],
        [118.6804, 132.9839],
        [ 21.0723,  37.0337],
        [101.9328, 119.1129]], grad_fn=<AddBackward0>)

In [26]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [27]:
import torch.nn as nn

In [28]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [29]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [30]:
from torch.utils.data import TensorDataset

In [31]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [32]:
from torch.utils.data import DataLoader

In [33]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [34]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 91.,  87.,  65.],
        [ 68.,  97.,  70.],
        [ 92.,  87.,  64.]])
tensor([[118., 134.],
        [ 20.,  38.],
        [ 80., 102.],
        [102., 120.],
        [ 82., 100.]])


In [35]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2405, -0.1921, -0.4674],
        [-0.1603, -0.2926, -0.3295]], requires_grad=True)
Parameter containing:
tensor([-0.0534,  0.0760], requires_grad=True)


In [36]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.2405, -0.1921, -0.4674],
         [-0.1603, -0.2926, -0.3295]], requires_grad=True),
 Parameter containing:
 tensor([-0.0534,  0.0760], requires_grad=True)]

In [37]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-50.5852, -45.3985],
        [-68.7654, -61.3480],
        [-73.8377, -72.1887],
        [-50.1451, -41.0484],
        [-67.8149, -62.1389],
        [-50.6336, -45.2662],
        [-69.0407, -61.3849],
        [-74.5457, -72.6785],
        [-50.0967, -41.1806],
        [-68.0418, -62.3081],
        [-50.8604, -45.4354],
        [-68.8138, -61.2157],
        [-73.5625, -72.1518],
        [-49.9183, -40.8792],
        [-67.7665, -62.2712]], grad_fn=<AddmmBackward0>)

In [38]:
# Import nn.functional
import torch.nn.functional as F

In [39]:
# Define loss function
loss_fn = F.mse_loss

In [40]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(22593.3867, grad_fn=<MseLossBackward0>)


In [41]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [42]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [43]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 298.4037
Epoch [20/100], Loss: 372.6094
Epoch [30/100], Loss: 454.0347
Epoch [40/100], Loss: 323.7877
Epoch [50/100], Loss: 53.7244
Epoch [60/100], Loss: 137.9709
Epoch [70/100], Loss: 73.9274
Epoch [80/100], Loss: 35.2346
Epoch [90/100], Loss: 28.3720
Epoch [100/100], Loss: 46.9680


In [44]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.3492,  71.8351],
        [ 79.1717,  97.5688],
        [122.4297, 137.1969],
        [ 28.6271,  45.6771],
        [ 92.3186, 108.7299],
        [ 57.2035,  70.8563],
        [ 78.4294,  97.0471],
        [122.4428, 137.5067],
        [ 29.7728,  46.6559],
        [ 92.7219, 109.1869],
        [ 57.6069,  71.3134],
        [ 78.0260,  96.5901],
        [123.1721, 137.7185],
        [ 28.2238,  45.2201],
        [ 93.4643, 109.7086]], grad_fn=<AddmmBackward0>)

In [45]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [46]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[54.3648, 68.4509]], grad_fn=<AddmmBackward0>)